version: "3.9"

services:
  api:
    build:
      context: ../../
      dockerfile: infra/docker/python.Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app/apps/api
    volumes:
      - ../../apps/api:/app/apps/api
    env_file:
      - ../../apps/api/.env.example
    environment:
      OPENFUSE_ENVIRONMENT: development
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ../../
      dockerfile: infra/docker/python.Dockerfile
    command: celery -A app.services.workflows.worker worker --loglevel=info
    working_dir: /app/apps/api
    volumes:
      - ../../apps/api:/app/apps/api
    env_file:
      - ../../apps/api/.env.example
    depends_on:
      - redis
      - postgres

  web:
    build:
      context: ../../
      dockerfile: infra/docker/node.Dockerfile
    command: pnpm dev
    working_dir: /app/apps/web
    volumes:
      - ../../apps/web:/app/apps/web
      - node_modules:/app/apps/web/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: openfuse
      POSTGRES_USER: openfuse
      POSTGRES_PASSWORD: openfuse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  node_modules:
  postgres_data:
