[project]
name = "openfuse-common"
version = "0.1.0"
description = "Shared utilities for OpenFuse services"
authors = [
  { name = "OpenFuse Contributors", email = "opensource@openfuse.io" }
]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "pydantic>=2.6.0,<3",
  "httpx>=0.27.0,<1"
]

[project.optional-dependencies]
test = [
  "pytest>=8.0",
  "pytest-asyncio>=0.23"
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"
